<?php

namespace App\Services\SeoAi;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * Everything the two providers share: the prompt, the cleanup and the shape.
 *
 * **One locale per call.** The module originally asked for all six languages in
 * a single request, roughly 4 000 words of JSON. That is survivable against a
 * large hosted model and hopeless against a 4B model on a CPU: measured on this
 * server, generation runs at about 6-14 tokens/second, so one combined call is
 * twenty to forty minutes during which a single malformed brace loses the lot.
 *
 * Splitting it costs nothing on OpenAI and is what makes the local model usable:
 * each response is short enough to stay valid JSON, a language that fails does
 * not take the other five with it, and the page is still complete because the
 * publisher only needs the locales that came back.
 */
abstract class AbstractSeoGenerator implements SeoGenerator
{
    /** One locale's worth of copy, or null if this locale could not be produced. */
    abstract protected function generateLocale(array $context, string $locale): ?array;

    public function generate(array $context): array
    {
        $result = [];

        foreach (array_keys(config('goodtriplove.locales')) as $locale) {
            try {
                $data = $this->generateLocale($context, $locale);
            } catch (\Throwable $e) {
                // A provider outage on one language is not a reason to lose the
                // page. It is a reason to say which language is missing.
                Log::warning('seo-ai: locale generation failed', [
                    'locale' => $locale,
                    'provider' => $this->describe(),
                    'message' => $e->getMessage(),
                ]);

                continue;
            }

            if ($data === null) {
                continue;
            }

            $normalized = $this->normalize($data, $locale);

            // An empty object is valid JSON, and the first production run
            // stored six pages built entirely out of normalize()'s defaults.
            // A page with no body is not a page.
            if (! $normalized['sections']) {
                Log::warning('seo-ai: model returned no body', [
                    'locale' => $locale,
                    'provider' => $this->describe(),
                ]);

                continue;
            }

            $result[$locale] = $normalized;
        }

        if (! $result) {
            throw new RuntimeException('No locale could be generated by '.$this->describe().'.');
        }

        return $result;
    }

    /**
     * The instruction sent for a single language.
     *
     * The factual rules are the important part and are deliberately blunt: an
     * invented opening time or "best restaurant in Lisbon" award is worse for
     * this site than no page at all.
     */
    protected function prompt(array $context, string $locale): string
    {
        $catalogue = json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        $language = config('goodtriplove.locales.'.$locale.'.name', $locale);

        return <<<PROMPT
You are the SEO editorial engine for GoodTripLove, a video-first travel discovery platform.
Write ONE useful editorial landing page, entirely in {$language}.

CATALOGUE_CONTEXT contains the real material this page must be built from:
`videos` are creator videos published on GoodTripLove (their titles and channel
names are facts you may cite), `places` are listed businesses, and
country/city/category name the subject. `places` is often empty — that is
normal, write from the videos in that case and never pretend places exist.

STRICT FACTUAL RULES:
- Use only facts, video titles, channel names and businesses contained in CATALOGUE_CONTEXT below.
- Never invent ratings, prices, opening hours, awards, addresses, statistics, events, transport times, or claims of being "the best".
- Do not mention that this text was generated by AI.
- Do not keyword-stuff. Write naturally in {$language}, not a translation.
- Write 4 to 6 sections. Each has a heading and 1 to 3 substantial paragraphs.
- Aim for 450-900 words where the catalogue supports it.
- Include 3 to 5 FAQs answerable from the context or general, non-controversial travel guidance.
- Refer naturally to watching the videos on GoodTripLove. Do not invent view counts or rankings.

Return STRICT JSON only. No Markdown, no code fences, no commentary, no reasoning.
Exactly this shape:
{
  "slug": "ascii-url-slug",
  "title": "SEO title, 65 characters maximum",
  "meta_description": "110 to 180 characters",
  "h1": "page heading",
  "excerpt": "1-2 sentence introduction",
  "keywords": ["keyword one", "keyword two"],
  "sections": [{"heading": "...", "paragraphs": ["...", "..."]}],
  "faq": [{"question": "...", "answer": "..."}]
}

CATALOGUE_CONTEXT:
{$catalogue}
PROMPT;
    }

    /**
     * The shape the model must return, as a JSON schema.
     *
     * `format: "json"` alone is not enough and is how the first real run
     * produced six empty pages: it constrains SYNTAX, and the cheapest valid
     * JSON is `{}`. A small model satisfies that and stops. Requiring the keys
     * and a minimum number of sections and paragraphs is what makes it write.
     */
    protected function responseSchema(): array
    {
        $paragraphs = [
            'type' => 'array',
            'minItems' => 2,
            'items' => ['type' => 'string', 'minLength' => 180],
        ];

        return [
            'type' => 'object',
            'properties' => [
                'slug' => ['type' => 'string'],
                'title' => ['type' => 'string', 'minLength' => 20],
                'meta_description' => ['type' => 'string', 'minLength' => 110],
                'h1' => ['type' => 'string', 'minLength' => 15],
                'excerpt' => ['type' => 'string', 'minLength' => 60],
                'keywords' => ['type' => 'array', 'minItems' => 3, 'items' => ['type' => 'string']],
                'sections' => [
                    'type' => 'array',
                    'minItems' => 4,
                    'items' => [
                        'type' => 'object',
                        'properties' => [
                            'heading' => ['type' => 'string', 'minLength' => 8],
                            'paragraphs' => $paragraphs,
                        ],
                        'required' => ['heading', 'paragraphs'],
                    ],
                ],
                'faq' => [
                    'type' => 'array',
                    'minItems' => 3,
                    'items' => [
                        'type' => 'object',
                        'properties' => [
                            'question' => ['type' => 'string', 'minLength' => 10],
                            'answer' => ['type' => 'string', 'minLength' => 80],
                        ],
                        'required' => ['question', 'answer'],
                    ],
                ],
            ],
            'required' => ['slug', 'title', 'meta_description', 'h1', 'excerpt', 'sections', 'faq'],
        ];
    }

    /**
     * Pulls a JSON object out of whatever the model actually returned.
     *
     * Small local models wrap their answer in prose, in Markdown fences, or —
     * Qwen3 does this by default — in a <think> reasoning block. A parser that
     * only strips fences fails on every single one of those, and the failure
     * reads as "invalid JSON" with no clue why. So: drop the reasoning, drop the
     * fences, then take the outermost balanced object.
     */
    protected function decodeJson(string $text): ?array
    {
        // Reasoning blocks, closed or left dangling by a token limit.
        $text = preg_replace('~<think>.*?</think>~is', '', $text) ?? $text;
        $text = preg_replace('~<think>.*$~is', '', $text) ?? $text;

        $text = trim($text);
        $text = preg_replace('/^```(?:json)?\s*/i', '', $text) ?? $text;
        $text = preg_replace('/\s*```$/', '', $text) ?? $text;

        $decoded = json_decode(trim($text), true);

        if (is_array($decoded)) {
            return $decoded;
        }

        // Fall back to the outermost {...}: models like to add a closing
        // sentence after the object.
        $start = strpos($text, '{');
        $end = strrpos($text, '}');

        if ($start === false || $end === false || $end <= $start) {
            return null;
        }

        $decoded = json_decode(substr($text, $start, $end - $start + 1), true);

        return is_array($decoded) ? $decoded : null;
    }

    /** Trims every field to something the database and the page can hold. */
    protected function normalize(array $data, string $locale): array
    {
        $sections = collect($data['sections'] ?? [])
            ->filter(fn ($s) => is_array($s) && filled($s['heading'] ?? null))
            ->map(fn ($s) => [
                'heading' => Str::limit(strip_tags((string) $s['heading']), 180, ''),
                'paragraphs' => collect($s['paragraphs'] ?? [])
                    ->map(fn ($p) => trim(strip_tags((string) $p)))
                    ->filter()->take(3)->values()->all(),
            ])
            ->take(6)->values()->all();

        $faq = collect($data['faq'] ?? [])
            ->filter(fn ($f) => is_array($f) && filled($f['question'] ?? null) && filled($f['answer'] ?? null))
            ->map(fn ($f) => [
                'question' => strip_tags((string) $f['question']),
                'answer' => strip_tags((string) $f['answer']),
            ])
            ->take(5)->values()->all();

        return [
            'locale' => $locale,
            'slug' => Str::slug((string) ($data['slug'] ?? $data['h1'] ?? 'discover')),
            'title' => Str::limit(strip_tags((string) ($data['title'] ?? 'GoodTripLove')), 180, ''),
            'meta_description' => Str::limit(strip_tags((string) ($data['meta_description'] ?? '')), 320, ''),
            'h1' => Str::limit(strip_tags((string) ($data['h1'] ?? $data['title'] ?? 'GoodTripLove')), 220, ''),
            'excerpt' => trim(strip_tags((string) ($data['excerpt'] ?? ''))),
            'keywords' => collect($data['keywords'] ?? [])
                ->map(fn ($k) => trim(strip_tags((string) $k)))
                ->filter()->take(12)->values()->all(),
            'sections' => $sections,
            'faq' => $faq,
        ];
    }
}
