<?php

namespace App\Services\SeoAi;

use App\Models\SeoAiSetting;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use RuntimeException;

class OpenAiSeoGenerator
{
    public function generate(array $context): array
    {
        $settings = SeoAiSetting::current();
        // Not env(): the deploy runs `config:cache`, after which env() returns
        // null and this fallback silently stops existing.
        $apiKey = $settings->api_key ?: config('seo_ai.openai_api_key');
        if (!$apiKey) {
            throw new RuntimeException('OpenAI API key is not configured.');
        }

        $locales = array_keys(config('goodtriplove.locales'));
        $model = $settings->model ?: config('seo_ai.openai_model');
        $prompt = $this->prompt($context, $locales);

        $response = Http::timeout(120)->retry(2, 1500)
            ->withToken($apiKey)
            ->acceptJson()
            ->post('https://api.openai.com/v1/responses', [
                'model' => $model,
                'input' => $prompt,
                'store' => false,
                'temperature' => 0.35,
            ]);

        if (!$response->successful()) {
            throw new RuntimeException('OpenAI request failed: HTTP '.$response->status().' '.Str::limit($response->body(), 500));
        }

        $text = $this->extractOutputText($response->json());
        $json = json_decode($this->cleanJson($text), true);
        if (!is_array($json) || !isset($json['translations']) || !is_array($json['translations'])) {
            throw new RuntimeException('OpenAI returned invalid SEO JSON.');
        }

        $result = [];
        foreach ($locales as $locale) {
            $data = $json['translations'][$locale] ?? null;
            if (!is_array($data)) continue;
            $result[$locale] = $this->normalize($data, $locale);
        }

        return $result;
    }

    private function prompt(array $context, array $locales): string
    {
        $catalogue = json_encode($context, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        $localeList = implode(', ', $locales);

        return <<<PROMPT
You are the SEO editorial engine for GoodTripLove, a video-first travel discovery platform.
Generate ONE useful editorial landing page in ALL these locales: {$localeList}.

STRICT FACTUAL RULES:
- Use only facts and named businesses/places contained in CATALOGUE_CONTEXT below.
- Never invent ratings, prices, opening hours, awards, addresses, statistics, events, transport times or claims of being "the best" unless explicitly supported.
- Do not mention that text was generated by AI.
- Do not keyword-stuff.
- Make each language natural, not a literal translation.
- Each locale must contain 4-6 sections, each with a heading and 1-3 substantial paragraphs.
- Target roughly 450-900 words per locale where the available catalogue supports it.
- Include 3-5 useful FAQs answerable from the context or general non-controversial travel guidance; avoid unverifiable factual specifics.
- Refer to GoodTripLove naturally and invite users to explore the listed places/videos without fabricated claims.

Return STRICT JSON only, no Markdown fences, in exactly this shape:
{
  "translations": {
    "fr": {
      "slug": "ascii-url-slug",
      "title": "SEO title <= 65 chars",
      "meta_description": "110-180 chars",
      "h1": "page heading",
      "excerpt": "1-2 sentence introduction",
      "keywords": ["keyword 1", "keyword 2"],
      "sections": [
        {"heading": "...", "paragraphs": ["...", "..."]}
      ],
      "faq": [
        {"question": "...", "answer": "..."}
      ]
    }
  }
}
Provide an object for every locale requested.

CATALOGUE_CONTEXT:
{$catalogue}
PROMPT;
    }

    private function extractOutputText(array $payload): string
    {
        $chunks = [];
        foreach ($payload['output'] ?? [] as $item) {
            if (($item['type'] ?? null) !== 'message') continue;
            foreach ($item['content'] ?? [] as $content) {
                if (($content['type'] ?? null) === 'output_text' && isset($content['text'])) {
                    $chunks[] = $content['text'];
                }
            }
        }
        if (!$chunks) throw new RuntimeException('OpenAI response contained no output text.');
        return implode("\n", $chunks);
    }

    private function cleanJson(string $text): string
    {
        $text = trim($text);
        $text = preg_replace('/^```(?:json)?\s*/i', '', $text) ?? $text;
        $text = preg_replace('/\s*```$/', '', $text) ?? $text;
        return trim($text);
    }

    private function normalize(array $data, string $locale): array
    {
        $sections = collect($data['sections'] ?? [])->filter(fn ($s) => is_array($s) && filled($s['heading'] ?? null))
            ->map(fn ($s) => [
                'heading' => Str::limit(strip_tags((string) $s['heading']), 180, ''),
                'paragraphs' => collect($s['paragraphs'] ?? [])->map(fn ($p) => trim(strip_tags((string) $p)))->filter()->take(3)->values()->all(),
            ])->take(6)->values()->all();
        $faq = collect($data['faq'] ?? [])->filter(fn ($f) => is_array($f) && filled($f['question'] ?? null) && filled($f['answer'] ?? null))
            ->map(fn ($f) => ['question' => strip_tags((string) $f['question']), 'answer' => strip_tags((string) $f['answer'])])
            ->take(5)->values()->all();

        return [
            'locale' => $locale,
            'slug' => Str::slug((string) ($data['slug'] ?? $data['h1'] ?? 'discover')),
            'title' => Str::limit(strip_tags((string) ($data['title'] ?? 'GoodTripLove')), 180, ''),
            'meta_description' => Str::limit(strip_tags((string) ($data['meta_description'] ?? '')), 320, ''),
            'h1' => Str::limit(strip_tags((string) ($data['h1'] ?? $data['title'] ?? 'GoodTripLove')), 220, ''),
            'excerpt' => trim(strip_tags((string) ($data['excerpt'] ?? ''))),
            'keywords' => collect($data['keywords'] ?? [])->map(fn ($k) => trim(strip_tags((string) $k)))->filter()->take(12)->values()->all(),
            'sections' => $sections,
            'faq' => $faq,
        ];
    }
}
